variables:
  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'ptraillecrresourcegroup' # Needs to already exist
  location: 'eastus'
  templateFile: './main.bicep'
  sourceFolder: 'quickstarts/microsoft.web/webapp-linux-managed-mysql/'

trigger:
- none

pool:
  vmImage: $(vmImageName)

name: Bicep deploy temlate

steps: 
- task: AzureCLI@2
  inputs:
    azureSubscription: 'MyARMSubscription'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az deployment group create --resource-group $(resourceGroupName) --template-file $(sourceFolder)$(templateFile) \
      --parameters administratorLogin=$(administratorLogin) administratorLoginPassword=$(administratorLoginPassword)